### ISSUE TITLE
Mong nhận được góp ý

### ISSUE THREAD

**Issue by namhoai167** [namhoai167/P4DS_Project#4]
Chào thầy và các bạn, @wiuy3120 và mình đã hoàn thành đồ án, mong nhận được góp ý từ thầy và các bạn. Cảm ơn mọi người đã dành thời gian.

**Comment by vohieu00** [comment]
Hi anh/bạn,

Mình có một thắc mắc, câu hỏi đặt ra là tìm top 10 đạo diễn + diễn viên có điểm đánh giá cao từ đối tượng nữ 18-30 tuổi thì có nhất thiết phải giới hạn số lượng phim mà người đó đã tham gia vì có thể có các diễn viên/đạo diễn trẻ, số lượng phim họ tham gia vốn rất ít nhưng vẫn được đánh giá cao thì cách lọc dữ liệu như vậy sẽ vô tình "bỏ mất" dữ liệu về họ. Nếu không thì bạn ghi rõ lại câu hỏi "có nhiều phim đạt điểm có điểm bình chọn trung bình cao". 
Trên đây là ý kiến của cá nhân mình. Cảm ơn bạn đã bỏ thời gian đọc.

Thân, 
Võ Hiếu

À, thêm nữa là kiểm tra lại chính tả nha, một số chỗ viết sai với dùng từ không rõ ràng. (Ví dụ, "đánh gái" :))))

**Comment by viplazylmht** [comment]
@vohieu00 come on, bản thân comment của mình cũng viết sai chính tả mà đi đánh giá người khác "))

>...tuổi thì có nhất thiết phải _giói hạn_ số lượng phim ...

**Comment by vohieu00** [comment]
> @vohieu00 come on, bản thân comment của mình cũng viết sai chính tả mà đi đánh giá người khác "))
> 
> > ...tuổi thì có nhất thiết phải _giói hạn_ số lượng phim ...



> @vohieu00 come on, bản thân comment của mình cũng viết sai chính tả mà đi đánh giá người khác "))
> 
> > ...tuổi thì có nhất thiết phải _giói hạn_ số lượng phim ...

Shhh, khẽ thôi bạn :)))

**Comment by periheli** [comment]
> Hi anh/bạn,
> 
> Mình có một thắc mắc, câu hỏi đặt ra là tìm top 10 đạo diễn + diễn viên có điểm đánh giá cao từ đối tượng nữ 18-30 tuổi thì có nhất thiết phải giói hạn số lượng phim mà người đó đã tham gia vì có thể có các diễn viên/đạo diễn trẻ, số lượng phim họ tham gia vốn rất ít nhưng vẫn được đánh giá cao thì cách lọc dữ liệu như vậy sẽ vô tình "bỏ mất" dữ liệu về họ. Nếu không thì bạn ghi rõ lại câu hỏi "có nhiều phim đạt điểm có điểm bình chọn trung bình cao".
> Trên đây là ý kiến của cá nhân mình. Cảm ơn bạn đã bỏ thời gian đọc.
> 
> Thân,
> Võ Hiếu
> 
> À, thêm nữa là kiểm tra lại chính tả nha, một số chỗ viết sai với dùng từ không rõ ràng. (Ví dụ, "đánh gái" :))))

Cảm ơn bạn @vohieu00 đã góp ý

Về việc tại sao phải lọc số lượng phim:
- Mục đích của tụi mình là tìm ra đạo diễn (diễn viên) giỏi thông qua trung bình điểm tất cả các bộ phim của họ mà theo mình thì làm 1 2 bộ phim tốt thì chưa chắc là đã giỏi. 
- Thực  sự việc đánh giá này vẫn còn là chủ quan của nhóm mình và việc có nên lọc hay không hoặc lọc trên bao nhiêu bộ phim thì đó là vấn đề khó là khó xác định

Về việc chính tả và đặc biệt là chỗ dùng từ không rõ ràng thì không biết bạn có thể chỉ ra giúp nhóm mình để mình sửa ạ. Nếu được thì cảm ơn bạn rất nhiều vì chính tả thì mình có thể dò lại chứ việc dùng từ không rõ ràng khá khó để tự mình nhận ra

**Comment by viplazylmht** [comment]
Chào anh/bạn,

Nói chung là bài làm của nhóm cũng ấn tượng đấy, phần giới thiệu bộ dữ liệu rất chi tiết, lại còn để nguyên ông Tom Hiddleston mà mình thích lên đầu nữa xD, rồi phần khám phá các thuộc tính trong bộ dữ liệu cũng rất trực quan, vẽ phân phối các biến numberic cụ thể, dễ nhìn (sẽ trực quan hơn nữa nếu kẻ được các line mean or median lên).  
Ngoài ra, các bạn trình bày, giải thích cho các cell code cũng rất chi tiết, đọc vô là hiểu chứ không như nhóm của mình :3

Tuy nhiên nói đi cũng phải nói lại, còn một vài vấn đề về xử lý dữ liệu mà nó có thể ảnh hưởng tới phần đặt và trả lời câu hỏi phía sau:

 - Có vẻ như nhóm tính tỉ lệ giá trị thiếu nhưng lại không có hành động gì loại bỏ hay xử lý chúng nhỉ (chỉ bỏ các cột có tỉ lệ quá cao).
 - Về cột `year` và `date_published`, mình đã chạy thử code và phát hiện cột `year` hầu hết nếu không bằng nhau thì đều nhỏ hơn year của cột `date_published`.  Tại sao lại như vậy? Có thể là phim bị delay vì các yếu tố khách quan như có diễn viên bị thương, hoặc cả là năng lực của đạo diễn có hạn và ekip đã đánh giá sai tiến độ, whatever. Tất nhiên bọn này sẽ ảnh hưởng đến rating của phim rồi, nhưng nếu mà những phim như phim của chị đại bị delay từ tháng 9 sang tháng 3 năm sau thì lại là cả một vấn đề, ảnh hưởng mạnh đến yếu tố `season` của câu hỏi 2. Vì thế mình thấy giải pháp bỏ đi một cột như của nhóm là chưa khách quan lắm (vì nó chiếm tới 20% tổng số dữ liệu).

Dù sao thì phần trả lời câu 2 cũng khá chất lượng, I like it. Còn câu 1 thì mình cũng đánh giá là chưa rõ ràng, nhưng chưa bắt tay vào nghiên cứu thử là cụ thể nó chưa rõ ràng chỗ nào xD.  
Trên đây chỉ là đánh giá chủ quan của mình, nên là vẫn chúc nhóm 21 sẽ đạt được kết quả cao với đồ án môn học này.

Xin cảm ơn.

Duy

**Comment by namhoai167** [comment]
Cảm ơn bạn đã dành thời gian đọc và cho nhận xét rất chi tiết. Những đánh giá này rất có ích với nhóm mình. Mình xin trả lời một vài ý liên quan đến phần mình làm.
> Có vẻ như nhóm tính tỉ lệ giá trị thiếu nhưng lại không có hành động gì loại bỏ hay xử lý chúng nhỉ (chỉ bỏ các cột có tỉ lệ quá cao).

Phần của mình là dữ liệu ratings, mình loại bỏ cột thiếu trên 50% và để những cột còn lại dữ liệu thiếu cao nhất chỉ 7.6%. Mình cũng đã nghĩ đến việc điền thiếu bằng trung bình của cột đó, nhưng như thế sẽ là sai vì không khách quan với trung bình trọng số có sẵn trong dữ liệu. Và nếu điền với điều kiện không thay đổi trung bình trọng số chung thì lại sai khác so với các cột trung bình khác, nên hiện tại mình cũng không có cách để điền thiếu sao cho phù hợp. Với lại tỷ lệ ratings thiếu cao nhất 7.6% từ nữ dưới 18 cũng không ảnh hưởng đến bài làm của mình.
> Còn câu 1 thì mình cũng đánh giá là chưa rõ ràng, nhưng chưa bắt tay vào nghiên cứu thử là cụ thể nó chưa rõ ràng chỗ nào xD.

Câu 1 mình làm dưới góc độ người tìm phim theo đạo diễn và diễn viên và dùng khá nhiều bộ lọc lên dữ liệu, tuy nhiên lại chưa viết markdown một cách hệ thống. Mình sẽ khắc phục việc này trong commit tới.

Cảm ơn các bạn đã dành thời gian. Mình cũng chúc các bạn đạt kết quả tốt với đồ án này.

**Comment by periheli** [comment]
> Về cột `year` và `date_published`, mình đã chạy thử code và phát hiện cột `year` hầu hết nếu không bằng nhau thì đều nhỏ hơn year của cột `date_published`.  Tại sao lại như vậy? Có thể là phim bị delay vì các yếu tố khách quan như có diễn viên bị thương, hoặc cả là năng lực của đạo diễn có hạn và ekip đã đánh giá sai tiến độ, whatever. Tất nhiên bọn này sẽ ảnh hưởng đến rating của phim rồi, nhưng nếu mà những phim như phim của chị đại bị delay từ tháng 9 sang tháng 3 năm sau thì lại là cả một vấn đề, ảnh hưởng mạnh đến yếu tố `season` của câu hỏi 2. Vì thế mình thấy giải pháp bỏ đi một cột như của nhóm là chưa khách quan lắm (vì nó chiếm tới 20% tổng số dữ liệu).

Cảm ơn bạn @viplazylmht đã nêu lên một góp ý rất hay. 

Sau khi đã suy xét kỹ hơn cũng như sửa code để thử nghiệm thì mình có một số ý kiến sau muốn chia sẻ với bạn:
- Đầu tiên là thực sự mình chưa thể xác định được cột `year` lại khác với year trong `date_published` vì mô tả trên kaggle là year of release và date of release nên cột `year` theo ý bạn nói (và mình cũng đã nghĩ như vậy) là năm dự kiến.
- Giả sử suy nghĩ của mình và bạn đúng: theo những gì bạn nói thì mình nghĩ là bạn muốn xóa các phim bị delay nhưng vấn dề là làm sao để xác định hết các phim bị delay, chỉ dựa trên sự rõ ràng là không đủ (có thể phim bị delay nhưng vẫn được ra mắt đúng năm) . Điều quan trọng hơn khi mình thử làm theo cách xóa các dòng khác đó đi thì dẫn đến vấn đề là số lượng các phim trong các tháng đầu năm giảm rất nhiều (theo mình thì điều này là cực kỳ nguy hiểm khi mình phân tích chu kỳ) - khi thấy kết quả như vậy thì có lẽ bạn cũng đã hiểu vì sao dẫn đến kết quả này.
- Dữ liệu ở đây không đủ để phân tích chính xác nên mình nghĩ là không nên xét thêm việc phim có bị delay không mặc dù là nó có thể ảnh hưởng đến kết quả ở câu 2. Tất nhiên mình có thể giữ lại cột `year` tuy nhiên Câu 2 cần tháng và ngày nên mình cũng sẽ chỉ sử dụng cột `date_published` mà thôi .Và để tránh gây hiểu nhầm thì cách xóa cột `year` theo mình vẫn là một phương án chấp nhận được. Ở Câu 2 mình sẽ chấp nhận sự sai lệch do các phim bị delay gây ra nhưng sai lệch này tồn tại trên tất cả các tháng (liệu nó có còn là sai lệch???)

Nếu bạn có thêm các ý kiến khác về vấn đề này mình rất vui để thỏa luận thêm với bạn

Cảm ơn các bạn. Mình cũng chúc các bạn đạt kết quả tốt với đồ án này.

**Comment by viplazylmht** [comment]
@wiuy3120 Đúng vậy, phần nhập nhằng ở chỗ ngày xuất bản này khá phức tạp, và sai trên tất cả các tháng thì chính là sai lệch rồi. Tuy nhiên theo mình nghĩ thì nó không bị delay ở tất cả các tháng đâu, thay vào đó sẽ delay tới mùa xem phim chẳng hạn, tức là sẽ làm rõ rệt hơn cái yếu tố trending của đồ thị. 

Vì vậy giải pháp bỏ cột year có thể nói là làm đơn giản hoá vấn đề, nhưng cũng ít nhiều làm giảm mức ý nghĩa của mô hình xuống. Và thực tế mình cũng chưa có giải pháp nào hợp lý hơn cho trường hợp này luôn :v Good job bro
